/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4f16a3479319219e8d63cfa39085c035)
interface __BaseEnv_Env {
	MUSE_TOKENS: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
